### ISSUE TITLE
Cannot Resize Widget

### ISSUE THREAD

**Issue by arxenix** [EmmanueleVilla/renshuu_widget#8]
The widget is too small to display schedule content, and can't be resized.

Screenshot from stock pixel 8a: 
![Screenshot_20241003-021440](https://github.com/user-attachments/assets/fb693e31-cbd7-4da1-b6ae-1ab0f25fce29)

**Comment by EmmanueleVilla** [comment]
Thanks for the input! I will totally make it resizable in the next release!
